spring:
  profiles:
    active: ${profile.active}

---
# 生产
server:
  port: 8080

spring:
  config:
    activate:
      on-profile: pro

---
# 开发
server:
  port: 8081

spring:
  config:
    activate:
      on-profile: dev

---
# 测试
server:
  port: 8082


spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite::resource:Database\census.db

  config:
    activate:
      on-profile: test

---